### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wbl-nb** [zerorooot/FuckBilibiliVote#2]
B站现在有个评论区关键词索引，能不能随便把那个弄掉

**Comment by RUADOU** [comment]
能不能加个屏蔽up主推荐广告，好好看视频结果来个这个挡着感觉有点烦。

**Comment by zerorooot** [comment]
> 能不能加个屏蔽up主推荐广告，好好看视频结果来个这个挡着感觉有点烦。

这个可以考虑一下，给个视频链接，那个视频的几分几秒？

**Comment by zerorooot** [comment]
> B站现在有个评论区关键词索引，能不能随便把那个弄掉

在hd版里没见过这玩意，给个图示

**Comment by RUADOU** [comment]
> > 能不能加个屏蔽up主推荐广告，好好看视频结果来个这个挡着感觉有点烦。
> 
> 这个可以考虑一下，给个视频链接，那个视频的几分几秒？

https://www.bilibili.com/video/BV1rV4y1p7tZ
  1分24秒

**Comment by zerorooot** [comment]
> > > 能不能加个屏蔽up主推荐广告，好好看视频结果来个这个挡着感觉有点烦。
> > 
> > 
> > 这个可以考虑一下，给个视频链接，那个视频的几分几秒？
> 
> https://www.bilibili.com/video/BV1rV4y1p7tZ 1分24秒

6.85.0，无法复现问题。要不你再多找几个视频？
![Screenshot_2022-08-19-15-31-35-275_tv danmaku bili](https://user-images.githubusercontent.com/21277567/185567664-763d58df-f21d-4c12-9570-066167f21fa0.jpg)

**Comment by IJustWantANamePlease** [comment]
> > B站现在有个评论区关键词索引，能不能随便把那个弄掉
> 
> 在hd版里没见过这玩意，给个图示

ta指的应该是这个蓝色带了个放大镜的![Screenshot_2022-09-19-01-10-05-998_com.bilibili.app.in.jpg](https://user-images.githubusercontent.com/69347951/190919713-12b1cc26-b94d-4c07-9c3f-51fad613a317.jpg)

**Comment by zerorooot** [comment]
无计划
