### ISSUE TITLE
一键追番弹窗

### ISSUE THREAD

**Issue by 2053628642** [zerorooot/FuckBilibiliVote#4]
观看间谍过家家时，出现了点击追番的弹窗，影响观看体验，麻烦更新模块屏蔽一下此弹窗

**Comment by 2053628642** [comment]
![Screenshot_2022-08-21-07-54-01-930_tv danmaku bili](https://user-images.githubusercontent.com/93074770/185769770-49b5486c-f9c7-4403-83cd-d03f22107802.jpg)
还发现了附带广告的弹窗

**Comment by zerorooot** [comment]
网址&&几分几秒。
如果软件是版本4.1.3，点击https://www.bilibili.com/video/BV1N5411Q7UU，看看在15秒~30秒之间是否出现追番按键

**Comment by 2053628642** [comment]
无法打开该链接

**Comment by 2053628642** [comment]
软件4.1.3，会出现追番按键
![Uploading Screenshot_2022-08-21-11-20-25-562_tv.danmaku.bili.jpg…]()

**Comment by 2053628642** [comment]
其实追番按键无妨，最主要是这个广告链接

**Comment by 2053628642** [comment]
https://b23.tv/ep508404
21:50秒左右
