### ISSUE TITLE
出现了新的拦不住的弹窗

### ISSUE THREAD

**Issue by IJustWantANamePlease** [zerorooot/FuckBilibiliVote#5]
之前碰到过游戏推荐和别的乱七八糟弹窗，不过找不着了……
这有个“官方模板”弹窗，在00:17
https://www.bilibili.com/video/BV1Lt4y137LY

**Comment by IJustWantANamePlease** [comment]
以及是否能做个特定弹窗关闭屏蔽的选项呢？比如说up主弹幕，我觉得这个如果能保留也挺不错的

**Comment by zerorooot** [comment]
> 之前碰到过游戏推荐和别的乱七八糟弹窗，不过找不着了…… 这有个“官方模板”弹窗，在00:17 https://www.bilibili.com/video/BV1Lt4y137LY

这个hook的点找到了，不过hd版没有，偷懒一直没更新，不过这个视频在hd版倒是复现了，有空搞一搞

**Comment by zerorooot** [comment]
> 以及是否能做个特定弹窗关闭屏蔽的选项呢？比如说up主弹幕，我觉得这个如果能保留也挺不错的

可以考虑一下
